### ISSUE TITLE
setAttribute not toggle?

### ISSUE THREAD

**Issue by heff** [muxinc/custom-media-element#3]
The second param of [toggleAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute) isn't the value, unless I'm not understanding the usage here. 

https://github.com/muxinc/custom-media-element/blob/5d4bae32caada18e11b60c1ef0c1186cf7e9fd76/custom-media-element.js#LL236C12-L236C27

**Comment by luwes** [comment]
indeed it's a boolean force flag that toggles the "boolean" attribute (muted in this case) on and off.
similar to [classList.toggle](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle)

I think it's correct...
I learned about `toggleAttribute` this year 😅 just sneaks up on you sometimes these web API's.
@gkatsev and @cjpillsbury hadn't heard or used it either I believe. we had a chuckle about it

**Comment by heff** [comment]
Ahhh I see. I was reading the details wrong. "force" is a weird way to describe the second argument which is just the value you want to set. It's a weird function all together I think, but 🤷 .
